@php
    $typeLabels = ['image' => 'Images', 'video' => 'Videos', 'audio' => 'Audio', 'document' => 'Documents'];
@endphp

<div id="galleryComposer" class="mt-6 hidden rounded-[20px] border border-slate-200 bg-white p-5 shadow-[0_10px_22px_rgba(19,41,26,0.05)]">
    <div class="mb-4 flex items-center justify-between border-b border-slate-100 pb-3">
        <div class="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#51657c]">Upload media</div>
        <button type="button" onclick="toggleGalleryComposer()" class="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600">Close</button>
    </div>
    <form method="POST" action="{{ route('admin.gallery.store') }}" enctype="multipart/form-data" class="space-y-4">
        @csrf
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <div class="lg:col-span-2"><label class="text-sm font-medium text-slate-700">Media file</label><input class="form-input" type="file" name="media" accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv,.zip"><p class="mt-2 text-xs text-[#51657c]">Image, video, audio, or document up to 20 MB.</p></div>
            <div><label class="text-sm font-medium text-slate-700">Media URL</label><input class="form-input" type="url" name="image_url" value="{{ old('image_url') }}" placeholder="https://example.com/photo.jpg"></div>
            <div><label class="text-sm font-medium text-slate-700">Title</label><input class="form-input" type="text" name="title" value="{{ old('title') }}" required></div>
            <div><label class="text-sm font-medium text-slate-700">Slug</label><input class="form-input" type="text" name="slug" value="{{ old('slug') }}" required></div>
            <div><label class="text-sm font-medium text-slate-700">Category</label><select class="form-input" name="category_id"><option value="">Uncategorized</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></div>
            <div><label class="text-sm font-medium text-slate-700">Status</label><select class="form-input" name="status">@foreach (['published', 'draft', 'pending'] as $statusOption)<option value="{{ $statusOption }}" @selected(old('status', 'published') === $statusOption)>{{ ucfirst($statusOption) }}</option>@endforeach</select></div>
        </div>
        <button type="submit" class="rounded-xl bg-[#173b27] px-5 py-2.5 text-sm font-semibold text-white">Save media</button>
    </form>
</div>

<div class="mt-6 overflow-hidden rounded-[20px] border border-slate-200 bg-white shadow-[0_10px_22px_rgba(19,41,26,0.05)]">
    <div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4">
        <div class="flex flex-wrap items-center gap-2"><span class="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#51657c]">All media</span><span class="rounded-full bg-[#eaf7ea] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.18em] text-[#173b27]">{{ number_format($items->total()) }} total</span>@if ($activeFilters)<span class="rounded-full bg-[#fff7e6] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.18em] text-amber-700">Filters applied</span>@endif</div>
        <div class="flex items-center gap-2"><form method="GET" action="{{ route('admin.gallery') }}"><label for="gallery-type" class="sr-only">Filter by type</label><select id="gallery-type" name="type" onchange="this.form.submit()" class="h-10 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm text-slate-700"><option value="">All types</option>@foreach ($mediaTypes as $mediaType)<option value="{{ $mediaType }}" @selected($typeFilter === $mediaType)>{{ $typeLabels[$mediaType] ?? ucfirst($mediaType) }}</option>@endforeach</select></form>@if ($activeFilters)<a href="{{ route('admin.gallery') }}" class="rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-600">Reset</a>@endif</div>
    </div>
    <div class="min-h-[380px] overflow-x-auto"><table class="w-full min-w-[900px] border-collapse text-left"><thead><tr class="border-b border-slate-200 bg-[#f8fafc] text-[11px] font-semibold uppercase tracking-[0.12em] text-[#51657c]"><th class="w-12 px-5 py-3.5">#</th><th class="w-20 px-3 py-3.5">Preview</th><th class="px-3 py-3.5">Title</th><th class="px-3 py-3.5">Category</th><th class="px-3 py-3.5">Type</th><th class="px-3 py-3.5">Status</th><th class="px-3 py-3.5">Uploaded</th><th class="px-3 py-3.5">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 text-sm">
        @forelse ($items as $index => $item)
            @php $mediaTitle = $item->title ?: 'Untitled'; $mediaUrl = $item->image_url ?: ''; $mediaType = $item->media_type ?: 'image'; @endphp
            <tr class="align-middle transition hover:bg-[#f8fafc]"><td class="px-5 py-3 text-sm tabular-nums text-slate-500">{{ ($items->firstItem() ?? 1) + $index }}</td><td class="px-3 py-3"><button type="button" class="relative flex h-11 w-14 items-center justify-center overflow-hidden rounded-lg bg-slate-100 text-xs font-bold uppercase text-slate-400" data-preview-url="{{ $mediaUrl }}" data-preview-type="{{ $mediaType }}" data-preview-title="{{ $mediaTitle }}" onclick="openMediaPreview(this)" aria-label="Preview {{ $mediaTitle }}">@if ($mediaType === 'image' && $mediaUrl)<img src="{{ $mediaUrl }}" alt="" class="absolute inset-0 h-full w-full object-cover" onerror="this.remove()">@endif<span>{{ $mediaType === 'image' ? 'IMG' : strtoupper(substr($mediaType, 0, 3)) }}</span></button></td><td class="px-3 py-3"><div class="max-w-[260px] truncate font-semibold text-[#1b2433]">{{ $mediaTitle }}</div><div class="mt-0.5 max-w-[260px] truncate text-xs text-slate-400">{{ $item->slug }}</div></td><td class="px-3 py-3"><span class="inline-flex whitespace-nowrap rounded-full bg-red-50 px-2.5 py-1 text-xs font-semibold text-red-700">{{ $item->category?->name ?? 'Uncategorized' }}</span></td><td class="px-3 py-3 text-slate-600">{{ ucfirst($mediaType) }}</td><td class="px-3 py-3"><span class="inline-flex whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-semibold {{ $item->status === 'published' ? 'bg-green-50 text-green-700' : ($item->status === 'pending' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-500') }}">{{ ucfirst($item->status) }}</span></td><td class="whitespace-nowrap px-3 py-3 text-slate-600">{{ $item->created_at?->format('M d, Y') ?? '—' }}</td><td class="px-3 py-3"><div class="flex flex-wrap gap-1"><button type="button" data-preview-url="{{ $mediaUrl }}" data-preview-type="{{ $mediaType }}" data-preview-title="{{ $mediaTitle }}" onclick="openMediaPreview(this)" class="inline-flex rounded-lg px-2 py-1.5 text-xs font-semibold text-[#1E4FA3]">Preview</button><button type="button" onclick="openDeleteModal('{{ route('admin.gallery.delete', $item->id) }}', '{{ addslashes($mediaTitle) }}')" class="inline-flex rounded-lg px-2 py-1.5 text-xs font-semibold text-red-600">Delete</button></div></td></tr>
        @empty
            <tr><td colspan="8" class="px-5 py-12 text-center text-sm text-slate-500">{{ $activeFilters ? 'No media matches your filter.' : 'No media yet.' }}</td></tr>
        @endforelse
    </tbody></table></div>
    @include('admin.partials.pagination', ['paginator' => $items, 'ariaLabel' => 'Gallery pagination'])
</div>

<div id="mediaPreviewModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/70 p-4" onclick="closeMediaPreview()"><div class="w-full max-w-4xl rounded-[20px] bg-white p-5" onclick="event.stopPropagation()"><div class="flex justify-between"><div id="mediaPreviewTitle" class="font-semibold text-[#173b27]">Media preview</div><button type="button" onclick="closeMediaPreview()">Close</button></div><div id="mediaPreviewStage" class="mt-4 flex min-h-[120px] items-center justify-center"></div><p id="mediaPreviewUrl" class="mt-3 break-all text-xs text-[#51657c]"></p></div></div>

<script>
    function openMediaPreview(trigger) { const url = trigger.dataset.previewUrl || ''; const type = trigger.dataset.previewType || 'image'; const stage = document.getElementById('mediaPreviewStage'); if (!url || (!url.startsWith('/') && !/^https?:\/\//i.test(url)) || !stage) return; stage.textContent = ''; const media = type === 'video' ? document.createElement('video') : type === 'document' ? document.createElement('iframe') : document.createElement('img'); media.src = url; media.className = type === 'document' ? 'h-[60vh] w-full' : 'max-h-[60vh] max-w-full rounded-xl'; if (type === 'video') media.controls = true; if (type === 'audio') { const audio = document.createElement('audio'); audio.controls = true; audio.src = url; audio.className = 'w-full'; stage.appendChild(audio); } else stage.appendChild(media); document.getElementById('mediaPreviewTitle').textContent = trigger.dataset.previewTitle || 'Media preview'; document.getElementById('mediaPreviewUrl').textContent = url; document.getElementById('mediaPreviewModal').style.display = 'flex'; }
    function closeMediaPreview() { const modal = document.getElementById('mediaPreviewModal'); if (modal) modal.style.display = 'none'; }
</script>
